# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = 'centos6.3'
  config.vm.box_url = 'https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box'
  config.vm.customize ["modifyvm", :id, "--memory", 1024]
  config.vm.forward_port 80, 80
  config.vm.forward_port 443, 443
  config.vm.forward_port 53, 53
  config.vm.host_name = 'broker.example.com'
  
  config.vm.share_folder "manifests", "/home/vagrant/manifests", "manifests"
  config.vm.provision :shell, :inline => %{ \
    touch /var/log/origin-setup.log; \
    sudo yum update -y                                          | tee -a /var/log/origin-setup.log; \
    sudo /usr/bin/puppet module uninstall openshift/openshift_origin          | tee -a /var/log/origin-setup.log; \
    sudo /usr/bin/puppet module install openshift/openshift_origin            | tee -a /var/log/origin-setup.log; \
    sudo /usr/bin/puppet apply --verbose /home/vagrant/manifests/init.pp      | tee -a /var/log/origin-setup.log; \
    sudo /usr/bin/puppet apply --verbose /home/vagrant/manifests/configure.pp | tee -a /var/log/origin-setup.log; \
  
    sudo /sbin/service network restart                        | tee -a /var/log/origin-setup.log; \
    sudo /sbin/service activemq restart                       | tee -a /var/log/origin-setup.log; \
    sudo /sbin/service cgconfig restart                       | tee -a /var/log/origin-setup.log; \
    sudo /sbin/service cgred restart                           | tee -a /var/log/origin-setup.log; \
    sleep 5; \
    sudo /sbin/service openshift-cgroups restart              | tee -a /var/log/origin-setup.log; \
    sudo /sbin/service httpd restart                          | tee -a /var/log/origin-setup.log; \
    sudo /sbin/service openshift-broker restart               | tee -a /var/log/origin-setup.log; \
    sudo /sbin/service openshift-node-web-proxy restart       | tee -a /var/log/origin-setup.log; \
    sudo /sbin/service named restart                          | tee -a /var/log/origin-setup.log; \
    sudo /sbin/service mcollective restart                    | tee -a /var/log/origin-setup.log; \
    sudo /usr/sbin/oo-register-dns -h broker -n 127.0.0.1       | tee -a /var/log/origin-setup.log;
  }
end
