name 'openshift-openshift_origin'
version '0.1.8'

author 'Mojo Lingo, Red Hat with some spices from weLaika'
license 'ASL'
project_page 'https://github.com/matjack1/puppet-openshift_origin'
source 'git://github.com/matjack1/puppet-openshift_origin.git'
summary 'Module for installing Red Hat Openshift on Centos6'
description 'Configures OpenShift Origin broker, nodes and support servers'
dependency 'puppetlabs/ntp', '>=0.1.0'
dependency 'puppetlabs/stdlib', '>=2.6.0'
